### PR TITLE
products listed by location

### LINKED ISSUE #14: Feature: Get products by location
When the client performs a GET request to the products resource, a query string parameter of `location` should be supported to get all products whose `location` property contains the value of the query string parameter.

Invesitgate the `__contains` filtering mechanism.

https://tutorial.djangogirls.org/en/django_orm/#filter-objects

### PR DESCRIPTION
**Pull request by kritikillz931**
Users can now search by product location

## Changes

-Added filtering support for product location to views/product.py

`product_location = self.request.query_params.get('location', None)`

`if product_location is not None:
            def location_filter(product):
                if product.location == (product_location):
                    return True
                return False
            products = filter(location_filter, products)`

## Requests / Responses

**Request**

GET http://localhost:8000/products?location=Santa Maria

**Response**

HTTP/1.1 201 OK

```
[
    {
        "id": 4,
        "name": "H1",
        "price": 1448.54,
        "number_sold": 0,
        "description": "2004 Hummer",
        "quantity": 3,
        "created_date": "2019-05-24",
        "location": "Santa Maria",
        "image_path": null,
        "average_rating": "No Ratings"
    }
]
```

## Testing

- [ ] git fetch --all
- [ ] pull branch 14-productLocation
- [ ] using post man, LOGIN as (Username: steve) || (password: Admin8*)
- [ ] using post man, GET http://localhost:8000/products?location=Santa Maria
- [ ] confirm results are only showing "Santa Maria"

## Related Issues

- Fixes #14

### CODE REVIEW

**Review by gwynnemeeks — CHANGES_REQUESTED** [review]
The ticket wants you to use the filtering mechanism `__contains` for this feature. You have a good start with your code block. Please go back and try filtering using `__contains`

https://tutorial.djangogirls.org/en/django_orm/#filter-objects

**Comment by kritikillz931** [comment]
made the changes. converted the if clause to:

if product_location is not None:
            products = products.filter(location__contains=product_location)

results 

[
    {
        "id": 4,
        "name": "H1",
        "price": 1448.54,
        "number_sold": 0,
        "description": "2004 Hummer",
        "quantity": 3,
        "created_date": "2019-05-24",
        "location": "Santa Maria",
        "image_path": null,
        "average_rating": "No Ratings"
    },
    {
        "id": 98,
        "name": "Explorer Sport Trac",
        "price": 1611.83,
        "number_sold": 0,
        "description": "2000 Ford",
        "quantity": 4,
        "created_date": "2019-01-05",
        "location": "Santa Praxedes",
        "image_path": null,
        "average_rating": "No Ratings"
    }
]

**Comment by gwynnemeeks** [comment]
Make sure you commit and push those changes up. I'm not seeing them on this PR yet.

**Comment by kritikillz931** [comment]
sorry about that, should be good now

**Review by gwynnemeeks — APPROVED** [review]
approved!

**Pull request merged**
